export const SETTING_HINTS = {
  loopSpeed: "How fast the loop runs. Period in seconds is roughly 1 ÷ speed.",
  repeatPeriod: "Radial spacing between streak repeats along each beam.",
  streakLength: "How long each streak is along the beam, as a fraction of the repeat period.",
  streakCount: "Number of beams drawn each frame.",
  thickness: "Angular width of each beam at its thickest point.",
  cornerRadius: "How rounded the streak caps are (0 = flat ends).",
  centerVoid: "Empty radius at the center where no streaks are drawn.",
  jitter: "Static random angle offset per beam (not spin).",
  jitterSpin: "Clockwise spin speed for beams in the spin mix (rad/s). 0 = off.",
  jitterSpinMix: "Fraction of beams that use clockwise spin.",
  activeColors: "How many palette colors beams can pick from.",
  brightness: "Overall intensity multiplier for streak color.",
  coreWhite: "How much the streak core leans toward white vs beam color.",
  bloom: "Extra glow spread from overlapping streaks.",
  exposure: "Final brightness multiplier after compositing.",
  vignette: "Darkens the outer edges of the frame.",
  seed: "Changes the random layout of beams.",
  bgOpacity: "0 = fully transparent background (checkerboard in preview).",
  bgFill: "Solid background color behind streaks.",
  bgImage: "Use an uploaded image instead of a flat fill color.",
};
